api/urls.py
from django.conf.urls import url
#from .views import PostListView ,PostDetailView
from . import views

urlpatterns = [
    #path list/create/detail/delete or update 
    url(r'^$', views.PostListView.as_view(), name='list'), # if you used (from .views import PostListView ,PostDetailView) instead of ....from . import views... should be... views.PostListView.as_view()
    url(r'^create/$', views.PostCreateView.as_view(), name='create'), #should add create in the second line cause this is the original location or path 
    url(r'^comments/$', views.CommentListView.as_view(), name='comment-list'),
    url(r'^comment/$', views.CommentCreateView.as_view(), name='comment-create'),
    url(r'^(?P<post_slug>[-\w]+)/detail/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^(?P<post_slug>[-\w]+)/delete/$', views.PostDeletelView.as_view(), name='delete'), #we added /delete/ cause there are to ways etheir delete or update inside the detail
    url(r'^(?P<post_slug>[-\w]+)/update/$', views.PostUpdateView.as_view(), name='update'),
    url(r'^register/$', views.UserCreateView.as_view(), name='register'),
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
   

    ]

    

dblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('posta.urls', namespace="home")),

    url(r'^comments/', include('django_comments.urls')),

    url(r'^googly/', include('googly.urls' , namespace="googly")),
    url(r'^gitty/', include('gitty.urls' , namespace="gitty")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^twitty/', include('twitty.urls' , namespace="twitty")),
    url(r'^api/', include('api.urls' , namespace="api")),

]
if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posta/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.post_list, name='list'),
    url(r'^detail/(?P<post_slug>[-\w]+)/$', views.post_detail, name='detail'),

    url(r'^create/$', views.post_create, name='create'),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', views.post_delete, name='delete'),
    url(r'^update/(?P<post_slug>[-\w]+)/$', views.post_update, name='update'),
    url(r'^like_button/(?P<post_id>\d+)/$', views.like_button, name='like_button'),
    url(r'^signup/$', views.usersignup, name='signup'),
    url(r'^login/$', views.userlogin, name='login'),
    url(r'^logout/$', views.userlogout, name='logout'),
    
    ]

    

    

posta/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Fatmaa(models.Model):
	title = models.CharField(max_length=122)
	author= models.ForeignKey(User, default=1)
	slug= models.SlugField(unique=True)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True)
	timestamp =models.DateTimeField(auto_now_add=True)
	img= models.ImageField(null=True, blank=True , upload_to="post_images")

	draft = models.BooleanField(default=False)
	publish_date= models.DateField()



	def __str__(self):
		return self.title


	class Meta:
		ordering = ['title']

def create_slug(instance, new_slug=None):
	slug_value = slugify(instance.title)
	if new_slug is not None:
		slug_value = new_slug

	query = Fatmaa.objects.filter(slug = slug_value)
	if query.exists():
		slug_value= "%s-%s"%(slug_value, query.last().id)
		return create_slug(instance, new_slug=slug_value)
	return slug_value


def pre_save_Fatmaa_function(*args, **kwargs):
	instance = kwargs['instance']
	instance.slug = create_slug(instance)


			
pre_save.connect(pre_save_Fatmaa_function, sender=Fatmaa)

class Like(models.Model):
	user = models.ForeignKey(User)
	post= models.ForeignKey(Fatmaa)
	timestamp = models.DateTimeField(auto_now_add=True)
    

posta/forms.py
from django import forms
from .models import Fatmaa
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
	class Meta:
		model = Fatmaa
		fields = ['title' , 'content' ,'img', 'draft' ,'publish_date']

		widgets={'publish_date': forms.DateInput(attrs={'type':'date'})
		}


class UserSignUp(forms.ModelForm):
	class Meta:
		model= User
		fields=['username' , 'email', 'password']

		widgets={'password': forms.PasswordInput()}

class UserLogin(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput())

posta/views.py
from django.shortcuts import render , redirect
from .models import Fatmaa , Like
from .forms import PostForm , UserSignUp , UserLogin
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.http import Http404 , JsonResponse
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth import login, logout, authenticate


def usersignup(request):
	context = {}
	form = UserSignUp() #add the model form (usersignup) to a variable
	context['form']= form


	if request.method == "POST": #checks if there is any data submitted in the form
		form = UserSignUp(request.POST) #save the form with the data inside the variable
		if form.is_valid(): #checks if the form submited is correct 
			user= form.save() #save the form in user variable
			username = user.username #retrieve the username from the form
			password = user.password #retrieve the password from the form

			user.set_password(password) #hashing the password to make it more secure (hide password)
			user.save() #save the form

			auth = authenticate(username=username, password=password) #used to login after signing up #authinticate the username and password of the user
			login(request, auth) #login the user to the page

			return redirect("home:list") #return to the list page
		messages.warning(request, form.errors) #an error message will be showen if the form is not valid
		return redirect("home:signup") #return to the signup page
	return render(request, 'signup.html', context) #return to the signup page if the user didn't submit any data to the form


def userlogin(request):
	context = {}
	form = UserLogin() #add the form (usersignup) to a variable #note: it is not a model form ; it is a form
	context['form']= form


	if request.method == "POST":
		form = UserLogin(request.POST)
		if form.is_valid():
			#note: we should always use cleaned_data when using a form of type form 
			some_username = form.cleaned_data['username'] #retrieve the username from the form 
			some_password = form.cleaned_data['password'] #retrieve the password from the form

			auth = authenticate(username=some_username, password=some_password)  #authinticate the username and password of the user #checks if there is a username with this password
			if auth is not None: #checks the username and the password are correct and exists in the database 
				login(request, auth)
				return redirect("home:list")
			messages.warning(request, 'Incorret Username/Password combination') #an error message will show if the username or the password is not correct 
			return redirect("home:login")
		messages.warning(request, form.errors)#an error message will be showen if the form is not valid
		return redirect("home:login")
	return render(request, 'login.html', context) #return to the signup page if the user have not submit yet any data to the form

def userlogout(request):
	logout(request) 
	return redirect("home:login")


def post_list(request):
	today = timezone.now().date() #a function to display time

	if request.user.is_staff:#checks if the current user is from the stuff 
		objects=Fatmaa.objects.all() #retrieve or show all the model Fatmaa objects including the draft and not published posts to the stuff user 
	else:
		objects= Fatmaa.objects.filter(draft=False, publish_date__lte=today) #show only the posts with no draft or the publish posts to the normal user

	query= request.GET.get('q') #get whatever inside the GET request (q) 
	if query: #if query has data inside 
		objects=objects.filter(

			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)
			).distinct() #filter or find the wanted posts based on the title , content , first name and last name

		#objects= Fatmaa.objects.all().order_by('-title', '-id')
	paginator = Paginator(objects, 3) #Show 3 objects per page

	number = request.GET.get('page') #get the number of the page the object is located in #get whatever inside the GET request (page) #note: page is a number
	try:
		objects = paginator.page(number) #show the specific object and its specific page number
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		objects = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results or empty
		objects = paginator.page(paginator.num_pages)

	context ={"post_items": objects, "today": today}
	return render(request, "list.html", context)



def post_detail(request, post_slug):
	today= timezone.now().date()
	item = Fatmaa.objects.get(slug=post_slug) #retrieve the object with the specific slug (detail of a specific object)
	liked=False
	if not (request.user.is_staff): #if the user is not a stuff user
		if item.draft or item.publish_date > today: #if the current date (today) is less than the future posts date (published-draft)  
			raise Http404 #show page not found 


	if request.user.is_authenticated(): #checks if the current user is logged in or not cause the user should be logged in to like a post or unlike
		if Like.objects.filter(post=item, user=request.user).exists(): #getting who did like and to which post 
			liked = True # will be true if there is a like in a post
		else:
			liked = False

	like_count= item.like_set.count() #count the number of likes in a post  #a set of likes in a post

	context ={"item": item , "liked" :liked, "liked_count": like_count}
	return render(request, "detail.html", context)



def post_create(request):
	if not request.user.is_staff:
		raise Http404

	form = PostForm(request.POST or None , request.FILES or None) #if there is a POST request (data submitted to form) and an image (request.FILES) or didn't submit any (none)
	if form.is_valid():
		fatma_post=form.save(commit=False) #the form should not be saved yet
		fatma_post.author= request.user #retrieve the current user from the form
		fatma_post.save() #save the form

		messages.success(request, "Awesome, you just added a blog post !")
		return redirect("home:list")
	context ={"form":form}
	return render(request, "post_create.html", context)

def post_update(request, post_slug):
	if not request.user.is_staff:
		raise Http404

	item = Fatmaa.objects.get(slug=post_slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=item)
	if form.is_valid():
		form.save()
		messages.info(request, "you just changed a blog post")
		return redirect("home:list")
	context ={"form":form, "item":item}
	return render(request, "post_update.html", context)

def post_delete(request, post_slug):
	if not request.user.is_staff:
		raise Http404
	Fatmaa.objects.get(slug=post_slug).delete() #delete a specific object or post
	messages.warning(request, "deleted")
	return redirect("home:list")



def like_button(request , post_id):
	post_object = Fatmaa.objects.get(id=post_id) #retrieve the specific object or post of specific id

	like, created = Like.objects.get_or_create(user=request.user, post=post_object) #checks wheather the current logged in user did like or not to a specific post  
	if created: # if the current loged in user did not has like this post previously , then create one 
		action = "like" #active the button to like
	else:
		like.delete() #delete the like object from the Like fields 
		action = "unlike" #unlike the post if the current logged in user who already has a like to the post
	like_count= post_object.like_set.count() 

	response={
	"like_count": like_count , "action":action

	}
	return JsonResponse(response, safe=False)


	
	
  

posta/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title> 
		{% block heading %} 
		{% endblock %}
	</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
	{% include "navbar.html"%}
	{% include "messages.html" %}
	<div class="container">
	{% block content%} 

	{% endblock content%}
    </div>
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/popper.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	
	

</body>
</html>

posta/templates/comments.html
{% load comments %}

{% get_comment_list for item as comments %}

{% for awesome in comments%}
	<div class="alert alert-info" role="alert"><b>{{ awesome.user_name }} said:</b> {{ awesome.comment|linebreaks}}</div>
{% endfor %}

{% get_comment_form for item as form %}

<form action="{% comment_form_target %}" method="POST">

	{% csrf_token %}

	<input type="hidden" name="name" value="{{request.user.username}}">
	<input type="hidden" name="email" value="{{request.user.email}}">
	<input type="text" name="comment" class="form-control input-lg">

	{{form.content_type}}
	{{form.object_pk}}
	{{form.timestamp}}
	{{form.security_hash}}

	<input type="hidden" name="next" value="{% url 'detail' post_slug=item.slug %}">

	<input type="submit" name="submit" class="btn btn-primary">

</form>

posta/templates/detail.html
{%extends "base.html" %}
{% load share %}


{% block content%}

<div class="card" style="width: 20rem;">
  <ul class="list-group list-group-flush">
  	{% if item.img %}
		    <img class="card-img-top" src="{{item.img.url}}" alt="Card image cap">
		{% endif %}
  	<div class="p-3 mb-2 bg-success text-white">{{item.title}}</div>
  	<div class="p-3 mb-2 bg-danger text-white">{{item.content}}</div>
	<div class="p-3 mb-2 bg-warning text-white">{{item.id}}</div>
	<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">Share on Facebook
	</a>
	
	<a href="https://twitter.com/home?status={{item.content|truncatechars:140|share}}%20{{request.build_absolute_uri}}"> Share on Twitter
	</a>
	<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{item.title|share}}&summary={{item.content|share}}&source={{request.build_absolute_uri}}">Share on Linkedin
	</a>
  </ul>
</div>
<br>
  <div class="btn btn-secondary" onclick="ajax_like()">
  	<span id="likes_count">{{liked_count}}</span>
    <span><i id= "heart" class="fa fa-heart {% if liked %} text-danger {% endif%}" aria-hidden="true"></i></span>
  </div>
  <br>
  {% include "comments.html" %}

  <script>
  function ajax_like()
  {

  	$.ajax(
  		{
  			type:'GET',
  			url:'{% url "like_button" post_id=item.id %}',
  			error:function(){ 
  				console.log("OMMGGG WHAT DID you do!")
  			},
  			success:function(data){
  				

  				$("#likes_count").text(data.like_count); 
  				if(data.action==="like"){
  					$("#heart").addClass("text-danger");
  				}
  				else{
  					$("#heart").removeClass("text-danger");
  				}
  			},
  	});
  }

  </script>


{% endblock content %}

posta/templates/fat.html
{% extends "base.html"%}

{% block title%} 
{% endblock%}


	<style>
	   .blue{background-color: blue;}

	   .green{background-color: green;}
	</style>

{% block body%}

<style>
    .blue{background-color: blue;}
    .green{background-color: green;}
</style>

<div class="row">
	<div class="col-6">
		<div class="col-6">
		</div>
	</div>
</div>

{% endblock body%}

posta/templates/list.html
{% extends "base.html" %}


{% block content%}


<div class="jumbotron">

  <h1 class="display-3">This is a post</h1>
  <a class="btn btn-primary btn-lg" href="{% url 'home:create' %}" role="button">create</a>
  
  <form action="{%url 'home:list'%}" method ="GET">

	<input type="text" name="q" placeholder="Search..." value="{{request.GET.q}}" >
	<input type="submit" value="search">

  </form>
</div>

<div class="row">
	{% for item in post_items %}
		<div class="card col-xs-12 col-md-4" style="width: 20rem;">
			{% if item.img %}
			    <img class="card-img-top" src="{{item.img.url}}" alt="Card image cap">
			{% endif %}
			<div class="card-body">
				<h4 class="card-title">Title: {{item.title}}<small>
					{{item.publish_date|timesince}}</small>
				</h4>

				{% if item.draft %}
					<span class="text-danger">
					Draft
					</span>
				{% endif %}

				{% if item.publish_date > today %}
					<span class="text-success">
					Future Post
					</span>	
				{% endif %}

				<h4 class="card-text">content: {{item.content|linebreaks|truncatechars:30}}</h4>
				<h4 class="card-title">ID: {{item.id}}</h4>
				<h4 class="card-title">Author: {{item.author.get_full_name}}</h4>
				<a href="{% url 'home:delete' post_slug=item.slug %}" class="btn btn-info">delete</a>
				<a href="{% url 'home:update' post_slug=item.slug %}" class="btn btn-danger">update</a>
				<a href="{% url 'home:detail' post_slug=item.slug %}" class="btn btn-success">detail</a>

			</div>
		</div>
		{% empty %}
			<span class=""></span>
	
	{% endfor %}




	<div class="pagination">
	<span class="step-links">
		{% if post_items.has_previous %}
			<a href="?page={{ post_items.previous_page_number }}&q={{request.GET.q}}">previous</a>
		{% endif %}

		<span class="current">
			Page {{ post_items.number }} of {{ post_items.paginator.num_pages }}
		</span>

		{% if post_items.has_next %}
			<a href="?page={{ post_items.next_page_number}}&q={{request.GET.q}}">next</a>
		{% endif %}
	</span>
</div>
{% endblock content %}
</div>

posta/templates/login.html
{%extends "base.html" %}
{% load crispy_forms_tags %}


{% block content%}
<form action="{%url 'home:login'%}" method="POST">
	{% csrf_token %}
	{{form|crispy}}
	<table>
		<tr>
			<td>
				<input class="btn btn-success" type="submit" value="login">
			</td>
			<td>
				<a href="{%url 'github_login' %}" class="btn btn-dark"><i class="fa fa-github-alt" aria-hidden="true"> Login using Github</i>
			</td>
			<td>
				<a href="{%url 'twitter_login' %}" class="btn btn-primary"><i class="fa fa-twitter" aria-hidden="true"> Login using Twitter</i></a>
			</td>
		</tr>
	</table>
	
		{% comment %}
		{% endcomment %}
	
</form>

{% endblock content%}

posta/templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

posta/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if request.user.is_stuff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:create' %}">Create Post</a>
      </li>
      {% endif %}
      {% if request.user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
      </li>
        <li class="nav-item">
          <a class="nav-link disabled">{{request.user}}</a>
      </li>
      {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'home:login' %}">Login</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'home:signup' %}">Signup</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="{{request.GET.q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

posta/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block heading %}
    create
{% endblock %}

{% block content%}

	<form action="{% url 'home:create' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
	{{form|crispy}}
	<input class="btn btn-success" type="submit" value="create">
	</form>

{% endblock content %}

posta/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block heading %}
   update
{% endblock %}

{% block content%}

	<form action="{% url 'home:update' post_slug=item.slug %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
	{{form|crispy}}
	<input type="submit" value="create">
	</form>
	
{% endblock content %}

posta/templates/signup.html
{%extends "base.html" %}
{% load crispy_forms_tags %}


{% block content%}
<form action="{%url 'home:signup'%}" method="POST">
	{% csrf_token %}
	{{form|crispy}}
	<input class="btn btn-success" type="submit" value="signup">
	
</form>

{% endblock content%}